info:
    app:
        description: master spring boot
        name: spring boot master class
        version: 3.0.0
    company:
        name: umraojaan
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: info, health, prometheus
    info:
        env:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
spring:
    application:
        name: demo
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
